oak:
  ros__parameters:
    camera:
      i_enable_imu: true
      i_enable_ir: false
      i_nn_type: none
      i_pipeline_type: depth
    left:
      i_resolution: '720P'
      i_fps: 30.0
      i_publish_topic: true
      i_color_order: RGB
    right:
      i_resolution: '720P'
      i_fps: 30.0
      i_publish_topic: true
      i_color_order: RGB
    nn:
      i_nn_config_path: depthai_ros_driver/mobilenet